import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const myFont = Inter({
  subsets: ["latin"],
  variable: "--my-font-family",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={myFont.className}>
        {children}
      </body>
    </html>
  );
}
