name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - master  # Adjusted to trigger on pushes to master
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Prepare Dockerfile
      run: cp ./docker/Dockerfile.user ./Dockerfile

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile.user
        push: true
        tags: patilxop/tranzit:latest  # Replace with your Docker Hub username and repository

    - name: Verify Pushed Image
      run: docker pull patilxop/tranzit:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          sudo docker pull patilxop/tranzit:latest
          sudo docker stop tranzit || true
          sudo docker rm tranzit || true
          sudo docker run -d --name tranzit -p 3005:3000 \
          -e DATABASE_URL=${{ secrets.DB_URL }} \
          -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
          -e NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }} \
          patilxop/tranzit:latest